# Generated by Django 3.0.8 on 2020-07-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscar_dados_banco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cod_badge',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
