# Generated by Django 3.0.8 on 2020-07-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscar_dados_banco', '0002_employee_cod_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='role_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
