# Generated by Django 3.0.8 on 2020-07-29 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscar_dados_banco', '0003_roles_role_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='role_id',
        ),
    ]
